# These are the default stages.
# You don't need to explicitly define them.
# But you could define any stages you want.
stages:
  - build
  - test
  - deploy

# This is the name of the job.
# You can choose it freely.
maven_build_and_deploy:
  # A job is always executed within a stage.
  # If no stage is set, it defaults to 'test'.
  stage: build
  # Since we require Maven for this job,
  # we can restrict the job to runners with a certain tag.
  # Of course, it is our duty to actually configure a runner
  # with the tag 'maven' and a working maven installation

  tags: 
    - marmotta

  # Here you can execute arbitrate terminal commands.
  # If any of the commands returns a non zero exit code the job fails.
  script:
    - echo "Building project with maven"
    - mvn -f marmotta/platform/marmotta-core/ clean install -DskipTests
    - mvn -f marmotta/platform/marmotta-ldp/ clean install -DskipTests
    - mvn -f marmotta/launchers/marmotta-webapp/ clean install -DskipTests
    #- echo $CI_CONFIG_PATH
    #- ls -al
    - cp marmotta/launchers/marmotta-webapp/target/marmotta.war .
    - cp marmotta/launchers/marmotta-webapp/target/marmotta.war /opt/apache-tomcat-9.0.2/webapps/


